### ISSUE TITLE
Support for custom markers

### ISSUE THREAD

**Issue by simo101** [mendixlabs/google-maps#12]
The old version of the google maps widget supported custom markers. Can this feature be added to this version so that the old one can be deprecated?

**Comment by mistaguy** [comment]
We will let you know as soon as possible

**Comment by simo101** [comment]
Any news on this item? This is currently preventing me from using the newer version.

**Comment by mistaguy** [comment]
We will work on this feature in the coming sprint starting next week.

**Comment by Andries-Smit** [comment]
Hi Simon, 

We added the requested feature https://appstore.home.mendix.com/link/app/48911/ version 1.4.3

Cheers,
Andries
