### ISSUE TITLE
get error could not find widget 'Googlemaps' in the widget directory ??

### ISSUE THREAD

**Issue by florishakvoort** [mendixlabs/google-maps#20]

**Comment by mistaguy** [comment]
@florishakvoort 
Please provide the version of the google maps widget you are using. as well as the mendix version. 
Steps to reproduce the error will be useful as well.

**Comment by Andries-Smit** [comment]
Dear Floris

We will close this issue as there are no details to reproduce the issue. 
A newer version is release since opening the issue
If the issue still persist please provide us with more information. 

Cheers, Andries
