### ISSUE TITLE
Add support for clickable markers

### ISSUE THREAD

**Issue by michaelgerritsen** [mendixlabs/google-maps#25]
It would be nice to able to click on a marker and go to a page. (passing the object)

**Comment by Andries-Smit** [comment]
Hi Michael,

Thank for submitting a feature request. We will discuss the request to see if we can put in it on our  backlog

Cheers,
Andries

**Comment by ssuijkerbuijk** [comment]
Any update on this since i'm also looking for a solution for this.

**Comment by ssuijkerbuijk** [comment]
I see there already is a pull request with this functionality in it. ANy update on this pull request? Can this be approved and pushed to the appstore?
@Andries-Smit

**Comment by Andries-Smit** [comment]
Dear Sander, 

The pull request #28 was rejected. (but its still open, i will close it)

At the moment we are redesigning the Google maps widget into a more generic Maps widget, supporting different map providers including google, and marker click events.

There is no formal release, and the beta is subject to change. If you like you can have a preview, feedback is appreciated.

https://github.com/FlockOfBirds/google-maps/releases/tag/v2.0.0-Beta

Cheers, Andries

**Comment by ssuijkerbuijk** [comment]
Hi Andries, Thanks for your reaction. :) Will take a look.

**Comment by Andries-Smit** [comment]
Dear Michael and Sander

The Google maps widget is succeeded by the a new `Maps` widget and does support click events.
https://appstore.home.mendix.com/link/app/108261/

Cheers, Andries
