### ISSUE TITLE
Google Maps retired version

### ISSUE THREAD

**Issue by JelleDekker** [mendixlabs/google-maps#26]
When running the application with this widget I get the following warning in the Mx console:

Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version

**Comment by ssuijkerbuijk** [comment]
Still receive the warning when using the Google Maps widget. Does the latest version still has the same bug?

**Comment by Andries-Smit** [comment]
Hi Jelle and Sander,

The google maps widget is now succeeded by the new `Maps` widget, which should not this message any longer. https://appstore.home.mendix.com/link/app/108261/

Cheers, Andries

**Comment by Andries-Smit** [comment]
If you dont want to migrate we also fixed it in v1.5.2 Available in the app store https://appstore.home.mendix.com/link/app/48911/
