### ISSUE TITLE
Support for maps without markers

### ISSUE THREAD

**Issue by JelleDekker** [mendixlabs/google-maps#27]
The widget allows a default location, but does not support rendering without any markers. I would expect the widget to work without markers, using default location.

**Comment by Andries-Smit** [comment]
The `default location` will not show a location, it is about centering the them map `Map center location when no locations are available.`

When no markers are added when set to Data source 'Static', at least one marker is required else en error message will be shown. 

As work around, if you like to show a map without marker, you use an other data source and not provide any markers at all (data view with empty context, xpath [flase()] or mf returning empty list)

What is the business case to support "No marker" on static maps?

**Comment by JelleDekker** [comment]
The business case is not having to create a workaround which returns an empty list of objects to not display any markers.

**Comment by Andries-Smit** [comment]
Yes, i understand what it solves for you. I like to know what use case there is for a map without a marker.

**Comment by JelleDekker** [comment]
In our app people the map is used to display an event. However the first user who submits the event can use the map to search for the correct address. When the map is used in this manner, it makes little sense to display a marker, as it's not known yet.

**Comment by Andries-Smit** [comment]
ok, will discuss it with the product owner

**Comment by Andries-Smit** [comment]
Implemented in v1.5.2 Available in the app store https://appstore.home.mendix.com/link/app/48911/
