### ISSUE TITLE
Feature went missing in new version: Marker labels

### ISSUE THREAD

**Issue by DblTS** [mendixlabs/google-maps#31]
In v2.0, it seems its no longer possible to have marker labels (on hover).
Can this be put back in v.2?

![image](https://user-images.githubusercontent.com/36757758/49156659-24657f00-f31e-11e8-9360-8bb4c027e957.png)

**Comment by SamuelMuloki** [comment]
Yah its currently not supported, we will discuss this with the product owner.

**Comment by Andries-Smit** [comment]
Hi Dirk

Version 2 is retracted, and is replaced by new `Maps` widget, which can be download through the app store
https://appstore.home.mendix.com/link/app/108261/

Please note that version 2 wont support labels either. 

Cheers, Andries

**Comment by DblTS** [comment]
Which version will support labels then? I was already using the 'Maps' version.
