### ISSUE TITLE
Feature: Plz make microflow datasource available with input param optional

### ISSUE THREAD

**Issue by DblTS** [mendixlabs/google-maps#32]
That way I can execute my logic in MF for returning location objects.
I don't always need an input param for that.

**Comment by Andries-Smit** [comment]
Hi Dirk,

Unfortunately we can not do this with the current limitation of building Mendix custom widgets.

As workaround: if the widget is not places in a data view, you can provide any entity, and the value will be empty and no error will be shown.

Please let me know if this works for you

Cheers, Andries
